language: ruby
rvm:
  - 2.2
  - 2.1
  - 2.0
before_install:
  - gem update --system
  - gem --version
script:
  - rake test
notifications:
  email:
    recipients:
    - secure: JoF6LwOaMjJJ80FO1OBpSm+9xhvqmcxxQGvXDfwDJqzkHPqvd/hL210CTE3/59lM6QPO/I5tvPa30ulD14kDqizm1d+rA1noqrQsO/x8eYDC70x2osyTlSDlILZpthXsEOmSFJCFqK9TSq5HvEvGIywtxd2W1SC7rBz0ZcL3MydgjPjLlMj2gniUumC8qNp8gLIVhx6wBowInXYq9q6HFFoPco1eGThlUcX8bvkRzrPNGw+IfSV4KPAjJhdkjtfjK4Tnbixew/v4coHUQyTb38WoFocpPIPqsVM8HU+9+N/YhpBFeWt+5Nks2Z7x323h868lJTiJDJUVXtgrHPPmc8uxnQ2A0kU/Cj5zkTfnakllTmUiiimKb5MVdLgxPqIWdt0/S6QO6q5XOLL5zOXO9Qz79MJkh4qEzDIv5MtyI7Fcpftof3jqzZ5URadIeg9klHsRKfwOBC1b4c2Na8PGSaYwaXNjhf9CPxj6L0YSjKvDLLF2AzWpeXPHTAiAdXAo6dqIOOdwK0XSWyEMhYKA52Aq0EjJmnEGQtbT7J65Ylxejy68hwC3a5tB6jWrXjoOre0BgkMvdzTTZJTdaJhMgP9HDfpuHl5rHGbaVgd+KpOVWCI6FyXkx/CRpFLXVPkKvMr101sLumRFh6u726wnjnKUGzu7VHR/3GZYujWgYxk=
